name: Build and Deploy to Azure

on:
  push:
    branches:
      - release
  workflow_dispatch:

env:
  IMAGE_NAME: mywebapi1234
  RESOURCE_GROUP: MyWebApiGroup2
  ACR_NAME: mywebapi1234

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Docker login to ACR
      run: az acr login --name ${{ env.ACR_NAME }}

    - name: Build Docker image
      run: docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .

    - name: Push Docker image
      run: docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy Docker image to Azure Web App
      run: |
        az webapp config container set \
          --name ${{ secrets.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --docker-custom-image-name ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --docker-registry-server-url https://${{ env.ACR_NAME }}.azurecr.io
    - name: Set PORT environment variable on Azure Web App
      run: |
        az webapp config appsettings set \
          --name ${{ secrets.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --settings PORT=80
